### ISSUE TITLE
create storyBoard for PVC

### ISSUE THREAD

**Issue by vSsongv** [plan-activity/Indian-Pocker#1]
indian pocker game의 PVC storyboard를 생성한다.

**Comment by hann3** [comment]
![storyboard](https://user-images.githubusercontent.com/48747805/147719357-f6fb8c78-8e33-40bb-87a2-ec842d5fe3bc.jpg)


스토리보드에 수정해야 할 사항이 있다면 말씀해 주세요.

**Comment by vSsongv** [comment]
1장씩 뽑는다는 표현 -> 1장씩 배정받는다 수정하시면 좋을것같아요

**Comment by hann3** [comment]
넵 단어 때문에 사용자가 직접 카드를 선택하는 걸로 오해할 여지가 있네요 수정하겠습니다

**Comment by h-sick** [comment]
매번 누가 이겼는지는 보여주는데 최종적으로 누가 이겼는지는 안보여주고 있는거 같은데

**Comment by vSsongv** [comment]
카드 보기보다도 카드 받기가 적절한 것 같네요!

**Comment by hann3** [comment]
서로 존중하는! 존댓말로 이슈 작성 부탁드릴게요 ^^ 
두분 의견 반영해서 수정하겠습니다~

**Comment by hann3** [comment]
![storyboard](https://user-images.githubusercontent.com/48747805/147719810-105e59ef-e7ee-43b3-abf5-edfaf54e1a27.jpg)

**Comment by h-sick** [comment]
숫자 비교 결과에 따라 단판 승부의 결과도 나와야 되지 않을까요?

**Comment by vSsongv** [comment]
한나님 효식님 코멘트 반영하셨나요?
