### ISSUE TITLE
create usecase for PVC

### ISSUE THREAD

**Issue by vSsongv** [plan-activity/Indian-Pocker#2]
indian pocker game의 PVC usecase를 생성한다.

**Comment by h-sick** [comment]
![image](https://user-images.githubusercontent.com/53730691/147719118-d7ec6225-d903-48d0-aff0-909b71af40b1.png)

pvc만 고려했을 떄 usecase에 더 추가될게 있을까요?

**Comment by vSsongv** [comment]
일단 show winner는 사용자가 하는 행위가 아닌 것 같아요. usecase는 사용자의 행위를 나타낸다고 생각하는데 3개 모두 사용자의 행위가 아니지 않나요?

**Comment by hann3** [comment]
사용자가 결과를 확인하는 것도 행위에 들어가지 않을까요?

**Comment by h-sick** [comment]
![image](https://user-images.githubusercontent.com/53730691/147719313-84e5a685-74d0-4249-b929-3f6ccda088d7.png)

방금 보고 생각나서 수정중이였는데 show Winner를 제외하면 사용자의 행위가 아닌가요?

**Comment by h-sick** [comment]
사용자가 결과를 확인하는거는 Compare Number에 종속된 Show Winner 에서 나와서 위의 이미지처럼 하면 되지 않을까요?

**Comment by vSsongv** [comment]
덱 초기화를 사용자가 하나요? 프로그램이 하고 사용자는 자기한테 주어진 카드만 볼 수 있는 거 아니었나요?

**Comment by h-sick** [comment]
아 그러네요 수정해서 다시 올릴게요

**Comment by hann3** [comment]
스토리보드대로 간다면 사용자가 웹사이트에서 할 수 있는 행위는 게임 시작하기, 카드 보기뿐인데 이 두 개가 아닐까요?

**Comment by h-sick** [comment]
![image](https://user-images.githubusercontent.com/53730691/147719541-161860a0-0ea9-462b-b1d1-cc467d9e407e.png)

**Comment by h-sick** [comment]
![image](https://user-images.githubusercontent.com/53730691/147719805-78396481-a912-4ab8-b69a-daf05e94e165.png)

최종 승리 여부도 보여줘야 될 것 같아서 `Show Total Winner` 추가했습니다

**Comment by vSsongv** [comment]
오른쪽에 시스템이 있고 그 시스템이 하는 일도 표시하면 될 것 같아요!
![image](https://user-images.githubusercontent.com/55029807/147719849-f3608aa3-10e8-4787-bb5f-ec5747d1df61.png)

**Comment by vSsongv** [comment]
게임
